comments/urls.py
from django.urls import path

from . import views

app_name = "comments"

urlpatterns = [
    path("list/", views.CommentListView.as_view(), name="list"),
    path("<int:pk>/edit/", views.EditCommentView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.DeleteCommentView.as_view(), name="delete"),
    path("create/<int:post>/", views.CreateCommentView.as_view(), name="create"),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("comments/", include("comments.urls", namespace="comments")),
    path("businesses/", include("businesses.urls", namespace="businesses")),
    path("users/", include("users.urls", namespace="users")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from posts import views as posts_views
from . import views

app_name = "core"

urlpatterns = [
    path("", posts_views.HomeView.as_view(), name="home"),
    path("search/", views.SearchView.as_view(), name="search"),
]


posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("<int:pk>", views.PostDetail.as_view(), name="detail"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("leave/", views.SignOutView.as_view(), name="leave"),
    path("leave/kakao/", views.kakao_leave, name="kakao-leave"),
    path(
        "leave/kakao/callback/", views.kakao_leave_callback, name="kakao-leave-callback"
    ),
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path(
        "login/kakao/callback/", views.kakao_login_callback, name="kakao-login-callback"
    ),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/",
        views.CompleteVerificationView.as_view(),
        name="complete-verification",
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

posts/models.py
from django.db import models

from core.models import TimeStampedModel
from users import models as users_model

# from businesses import models as business_models


class Photo(TimeStampedModel):

    """ Photo Model 정의 """

    caption = models.CharField(max_length=80, blank=True)
    file = models.ImageField(upload_to="post_photos")
    post = models.ForeignKey("Post", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Post(TimeStampedModel):

    """ Post Model 정의 """

    name = models.CharField(max_length=140)
    description = models.TextField(default="")
    businesses = models.ManyToManyField(
        "businesses.Business", related_name="posts", blank=True
    )
    user = models.ForeignKey(
        "users.User", related_name="posts", on_delete=models.SET(users_model.set_FkUser)
    )

    def __str__(self):
        return self.name

    def count_comments(self):
        comment = self.comments.all().count()
        return comment

    def first_photo(self):
        (photo,) = self.photos.all()[:1]
        return photo.file.url

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

posts/views.py
from django.views.generic import ListView, DetailView

from comments import forms as comments_forms
from . import models


class HomeView(ListView):

    """ HomeView 정의 """

    model = models.Post
    paginate_by = 12
    ordering = "created"
    paginate_orphans = 6
    context_object_name = "posts"


class PostDetail(DetailView):

    """ Post Detail View """

    model = models.Post

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        photos = self.object.photos.all().order_by("-created")

        context["form"] = comments_forms.CreateCommentForm()
        context["photos"] = photos
        return self.render_to_response(context)

templates/posts/post_detail.html
{% extends "base.html" %} 

{% block page_title %} 
{{post.name}} 
{% endblock page_title %} 

{% block content %}

<div class="container relative flex flex-col sm:w-75vh lg:w-1/1 md:w-3/4 xl:w-1/2 my-10 m-auto items-center border border-gray-400 sm:h-50vh & my-20 xl:h-75vh">
    <div class="relative top-0 flex w-full sm:h-10 mt-1 p-2 font-medium border-b border-gray-300">{{post.name}}</div>
    <div class="flex w-full h-full mb-1">
        <div class="flex flex-col w-1/2 overflow-y-auto">
            {% for photo in photos %}
                <ul class="my-1"><img src="{{photo.file.url}}" class=""></ul>
            {% endfor %}
        </div>
        <div class="flex flex-col w-1/2 border-b border-gray-300">
            <div class="flex flex-col sm:h-40 xl:h-25vh mt-1 p-1 overflow-y-auto">
                <div class="flex h-full overflow-y-auto mb-1 border-b border-gray-300">
                    {{post.description}}
                </div>
                <div class="flex h-10 overflow-y-auto">
                    {% if not post.businesses.all %}
                        <span class="text-lg font-medium text-gray-500 mx-24 mt-10">No Businesses</span>
                    {% endif %}
                        
                    {% for business in post.businesses.all %}
                        <a class="font-medium" href="{% url 'businesses:detail' business.pk %}">#{{business.name}}</a>
                    {% endfor %}   
                </div>
            </div>
            <div class="flex flex-col sm:h-40 xl:h-50vh mt-1">
                <div class="flex h-10 p-1 items-center border-b border-t border-gray-300">
                    <i class="far fa-comment mr-1"></i> {{post.comments.count}}
                </div>
                <div class="flex flex-col h-full p-1 overflow-y-auto">
                    {% for comment in post.comments.all %}
                    <div class="border-section">
                        <div class="flex justify-between">
                            <div class="flex mb-3">
                                <div>
                                    {% include "mixins/user/user_avatar.html" with user=comment.user h_and_w='w-10 h-10' %}
                                </div>
                                <div class="flex flex-col ml-2">
                                <a href="{% url 'users:profile' comment.user.pk %}" class="font-medium">{{comment.user.first_name}}</a>
                                <span class="text-sm text-gray-500">{{comment.created|date:'M Y'}}</span>
                                </div>
                            </div>
                            
                            {% if comment.user == user %}
                            <div class="flex">
                                <a href="{% url "comments:edit" comment.pk %}"><i class="fas fa-pen"></i></a>
                                <a href="{% url "comments:delete" comment.pk %}"><i class="fas fa-trash-alt"></i></a>
                            </div>    
                            {% endif %}
                            
                        </div>
                        <p>{{comment.comment}}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="flex h-15 my-1">
                <form class="flex w-full h-10" action="{% url "comments:create" post.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="comment">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/posts/post_list.html
{% extends "base.html" %}

{% block page_title %}
    Home
{% endblock page_title %}   

{% block content %}

    <div class="container mx-auto pb-10">
        <div class="flex flex-wrap mx-24 mt-10">
            {% for post in posts %}
                {% include 'mixins/post_card.html' with post=post %}
            {% endfor %}
        </div>
        <div class="flex items-center justify-center mx-auto container">
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}" class="text-500"><i class="fas fa-chevron-left fa-lg"></i></a>
        {% endif %}
            <span class="mx-3 font-medium text-lg">
                {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            </span>
        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}" class="text-500"><i class="fas fa-chevron-right"></i></a>
        {% endif %}
        </div>
    </div>
{% endblock content %}