comments/urls.py
from django.urls import path

from . import views

app_name = "comments"

urlpatterns = [
    path("list/", views.CommentListView.as_view(), name="list"),
    path("<int:pk>/edit/", views.EditCommentView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.DeleteCommentView.as_view(), name="delete"),
    path("create/<int:post>/", views.CreateCommentView.as_view(), name="create"),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("comments/", include("comments.urls", namespace="comments")),
    path("businesses/", include("businesses.urls", namespace="businesses")),
    path("users/", include("users.urls", namespace="users")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from posts import views as posts_views
from . import views

app_name = "core"

urlpatterns = [
    path("", posts_views.HomeView.as_view(), name="home"),
    path("search/", views.SearchView.as_view(), name="search"),
]


users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("leave/", views.SignOutView.as_view(), name="leave"),
    path("leave/kakao/", views.kakao_leave, name="kakao-leave"),
    path(
        "leave/kakao/callback/", views.kakao_leave_callback, name="kakao-leave-callback"
    ),
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path(
        "login/kakao/callback/", views.kakao_login_callback, name="kakao-login-callback"
    ),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/",
        views.CompleteVerificationView.as_view(),
        name="complete-verification",
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

users/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.core.mail import send_mail
from django.db import models
from django.shortcuts import reverse
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from core import managers


def set_FkUser():
    return User.objects.get(username="unknown")


class User(AbstractUser):

    """ Custom User Model 정의 """

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OTHER, "Other"),
    )

    LOGIN_EMAIL = "email"
    LOGIN_GITHUB = "github"
    LOGIN_KAKAO = "kakao"

    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_GITHUB, "Github"),
        (LOGIN_KAKAO, "Kakao"),
    )

    avatar = models.ImageField(upload_to="avatars", null=True, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=10, blank=True)
    bio = models.TextField(default="Hello", blank=True, null=True)
    birthdate = models.DateField(blank=True, null=True)
    businessman = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=20, default="", blank=True)
    login_method = models.CharField(
        choices=LOGIN_CHOICES, max_length=50, default=LOGIN_EMAIL
    )

    objects = managers.CustomUserManager()

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                "Verify BusanIn Account",
                strip_tags(html_message),
                settings.EMAIL_HOST_FROM,
                [self.email],
                fail_silently=False,
                html_message=html_message,
            )
            self.save()
        return

users/forms.py
from django import forms
from django.contrib.auth import password_validation

from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(username=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignUpForm(forms.ModelForm):

    """ SignUpForm Definition """

    class Meta:
        model = models.User
        fields = ("first_name", "last_name", "email")
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email Name"}),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"})
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError(
                "That email is already taken", code="existing_user"
            )
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password_validation.validate_password(password):
            if password != password1:
                raise forms.ValidationError("Password confirmation does not match")
            else:
                return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)

        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        user.username = email

        user.set_password(password)

        user.save()

users/views.py
import os
import requests
from django.contrib import messages
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login, logout
from django.contrib.messages.views import SuccessMessageMixin
from django.core.files.base import ContentFile
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView, DetailView, UpdateView, RedirectView

from core import mixins
from . import forms, models


class LoginView(mixins.LoggedOutOnlyMixin, SuccessMessageMixin, FormView):

    """ Log in View """

    template_name = "users/login.html"
    form_class = forms.LoginForm
    success_message = "로그인 되었습니다!"

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)

        if user is not None:
            login(self.request, user)

        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


class LogoutView(
    mixins.LoggedInOnlyMixin, mixins.NotFormSuceesMessageMixin, RedirectView
):

    """ Log out View """

    url = reverse_lazy("core:home")
    success_message = "로그아웃 되었습니다."

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class SignOutView(mixins.NotFormSuceesMessageMixin, RedirectView):

    """ Sign out View """

    url = reverse_lazy("core:home")
    success_message = "탈퇴되었습니다! 다시 만날 수 있었으면 좋겠네요!"

    def get(self, request, *args, **kwargs):
        try:
            login_method = request.user.login_method
            if login_method == models.User.LOGIN_KAKAO:
                return redirect(reverse("users:kakao-leave"), request)
            else:
                request.user.delete()
        except models.User.Exception:
            messages.error(f"탈퇴에 실패했습니다!")
        return super(SignOutView, self).get(request, *args, **kwargs)


class SignUpView(mixins.LoggedOutOnlyMixin, FormView):

    """ Sign Up View """

    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(SignUpView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)

        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


class CompleteVerificationView(mixins.NotFormSuceesMessageMixin, RedirectView):

    """ Verification Complete View """

    url = reverse_lazy("core:home")
    success_message = "인증이 완료되었습니다."

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(CompleteVerificationView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        try:
            user = models.User.objects.get(email_secret=self.kwargs["key"])
            user.email_verified = True
            user.email_secret = ""
            user.save()

        except models.User.DoesNotExist:
            messages.error(self.request, "사용자가 존재하지 않습니다.")
        return super(CompleteVerificationView, self).get(request, *args, **kwargs)


# 1. Request a user's Github identity
def github_login(request):
    client_id = os.environ.get("GH_ID")
    domain = os.environ.get("DOMAIN")
    redirect_uri = f"{domain}/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


class GithubException(Exception):
    pass


# 2. USers are redirected back to your site by Github
def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        code = request.GET.get("code", None)
        # Exchange the 'code' for an access token
        if code is not None:
            # Receive the content's formats depending on the Accpept header
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            # 3. User access token to access the API
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:
                raise GithubException("Can't get access token")
            else:
                access_token = token_json.get("access_token")
                profile_request = requests.get(
                    f"https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                profile_json = profile_request.json()
                username = profile_json.get("email", None)
                # Github login using OAuth
                if username is not None:
                    name = profile_json.get("name")
                    email = profile_json.get("email")
                    bio = profile_json.get("bio")
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            raise GithubException(
                                f"Please log in with: {user.login_method}"
                            )
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            email=email,
                            first_name=name,
                            username=email,
                            bio=bio,
                            login_method=models.User.LOGIN_GITHUB,
                            email_verified=True,
                        )
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    messages.success(request, f"Welcome back {user.first_name}")
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("Can't get your profile")
        else:
            raise GithubException("Can't get code")
    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


def kakao_leave(request):
    """ kakao 회원 탈퇴 """
    client_id = os.environ.get("KAKAO_ID")
    domain = os.environ.get("DOMAIN")
    redirect_uri = f"{domain}/users/leave/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


def kakao_leave_callback(request):
    try:
        code = request.GET.get("code", None)
        client_id = os.environ.get("KAKAO_ID")
        domain = os.environ.get("DOMAIN")
        redirect_uri = f"{domain}/users/leave/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)

        if error is not None:
            raise KakaoException("Can't get authorization code.")
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={
                "Authorization": f"Bearer {access_token}",
                "Content-type": "application/x-www-form-urlencoded;charset=utf-8",
            },
        )
        profile_json = profile_request.json().get("kakao_account")
        email = profile_json.get("email", None)

        leave_request = requests.post(
            f"https://kapi.kakao.com//v1/user/unlink",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        leave_id = leave_request.json().get("id", None)

        if leave_id is not None:
            user = models.User.objects.get(email=email)
            user.delete()
            messages.info(request, f"Good bye!")
            return redirect(reverse("core:home"))

    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("core:home"))


def kakao_login(request):
    client_id = os.environ.get("KAKAO_ID")
    domain = os.environ.get("DOMAIN")
    redirect_uri = f"{domain}/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_login_callback(request):
    try:
        code = request.GET.get("code", None)
        client_id = os.environ.get("KAKAO_ID")
        domain = os.environ.get("DOMAIN")
        redirect_uri = f"{domain}/users/login/kakao/callback"
        token_request = requests.get(

templates/users/leave.html
{% extends "base.html" %}

{% block page_title %}
    Closed Account
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}
    
{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 border p-6 border-gray-40">
        <form action="" method="post">
            {% csrf_token %}
            <p class="text-lg my-10 text-center">Do you want to leave?</p>
            <div class="flex justify-between mx-5">
                <input class="btn-link px-2 text-sm mr-5" type="submit" value="Leave">
                <a class="btn-link bg-red-500 px-2 text-sm" href="{% url 'core:home' %}"> Cancel </a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/users/login.html
{% extends "base.html" %}

{% block page_title %}
    Log In
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'partials/social_login.html' %}

        {% include 'mixins/auth/auth_form.html' with form=form cta="Log in" %}

        <div class="mt-5">
            <span class="mr-2">Don't have an account?</span>
            <a href="{% url "users:signup" %}" class="text-green-500 font-medium"">Sign up</a>
        </div>
    </div>
{% endblock content %}
    

templates/users/password-update.html
{% extends "base.html" %}

{% block page_title %}
    Update Password
{% endblock page_title %}

{% block content %}
    
<div class="min-h-75vh">
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include "mixins/auth/auth_form.html" with form=form cta="Update Password" %}
    </div>
</div>

{% endblock content %}

templates/users/profile-update.html
{% extends "base.html" %}

{% block page_title %}
    Update Profile
{% endblock page_title %}

{% block content %}
<div class="container lg:w-5/12 md:w-1/2 xl:1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

    {% include "mixins/auth/auth_form.html" with form=form cta="Update profile" %}

    <div class="mt-5">
        {% if user_obj.login_method == "email" %}
            <a href="{% url "users:password" %}" class="text-green-500 font-medium">Change Password</a>
        {% endif %}
    </div>

</div>
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_title %}
    Sign Up
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include 'partials/social_login.html' %}

        {% include 'mixins/auth/auth_form.html' with form=form cta="Sign up" %}

        <div class="mt-5">
            <span class="mr-2">Have an account?</span>
            <a href="{% url 'users:login' %}" class="text-green-500 font-medium">Log in</a>
        </div>
    </div>
{% endblock content %}
    

templates/users/user_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{user_obj.first_name}}'s Profile
{% endblock page_title %}

{% block content %}

<div class="min-h-75vh flex">
    {% include 'mixins/user/user_info.html' with user=user user_obj=user_obj %}
    <div class="container lg:w-6/12 md:w-1/2 xl:w-3/5 mx-auto my-10 flex flex-col p-6 border border-gray-400">
        <div class="text-lg mb-5">{{user_obj.bio}}</div>
        <div class="my-5">
        {% if user == user_obj %}
            <a href="{% url 'users:update' %}" class="btn-link px-2 text-sm">Edit Profile</a>
            <a href="{% url 'users:leave' %}"  class="btn-link px-2 text-sm">Close My Account</a>
        {% endif %}
        </div>
        <div class="flex flex-col">
            <div class="my-5">
                {% if user_obj.businessman %}
                    <span class="text-xl font-medium">{{user_obj.first_name}}'s Businesses</span>
                    {% if user == user_obj %}
                        <a href="{% url 'businesses:create' %}" class="mx-2 text-green-500 text-normal font-medium"><i class="fas fa-plus-circle"></i></a>
                    {% endif %}
                    <div class="flex">
                    {% for business in user_obj.businesses.all %}
                        {% include 'mixins/business/business_card.html' with business=business %}
                    {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}