businesses/urls.py
from django.urls import path
from . import views

app_name = "businesses"

urlpatterns = [
    path("create/", views.CreateBusinessView.as_view(), name="create"),
    path("<int:pk>/", views.BusinessDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditBusinessView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.BusinessPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photos",),
    path(
        "<int:business_pk>/photos/<int:photo_pk>/delete/",
        views.DeletePhotoView.as_view(),
        name="delete-photos",
    ),
    path(
        "<int:business_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photos",
    ),
    path("<int:pk>/delete/", views.DeleteBusinessView.as_view(), name="delete"),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("comments/", include("comments.urls", namespace="comments")),
    path("businesses/", include("businesses.urls", namespace="businesses")),
    path("users/", include("users.urls", namespace="users")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
    path("sentry-debug/", trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from posts import views as posts_views
from . import views

app_name = "core"

urlpatterns = [
    path("", posts_views.HomeView.as_view(), name="home"),
    path("search/", views.SearchView.as_view(), name="search"),
]


businesses/models.py
from django.db import models
from phone_field import PhoneField
from core.models import TimeStampedModel


class Photo(TimeStampedModel):

    """ Business Photo Model 정의 """

    caption = models.CharField(max_length=80, blank=True)
    file = models.ImageField(upload_to="business_photos")
    business = models.ForeignKey(
        "Business", related_name="photos", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.caption


class Business(TimeStampedModel):

    """ Business Model 정의 """

    name = models.CharField(max_length=80)
    description = models.TextField(default="")
    address = models.CharField(max_length=140)
    open_time = models.TimeField(blank=True)
    close_time = models.TimeField(blank=True)
    businessman = models.ForeignKey(
        "users.User", related_name="businesses", on_delete=models.CASCADE
    )
    phone = PhoneField(blank=True)

    def __str__(self):
        return self.name

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos


businesses/forms.py
from django import forms
from . import models


class CreateBusinessForm(forms.ModelForm):
    class Meta:
        model = models.Business
        fields = (
            "name",
            "description",
            "address",
            "open_time",
            "close_time",
            "phone",
        )

    def save(self, *args, **kwargs):
        business = super().save(commit=False)
        return business


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, *args, **kwargs):
        photo = super().save(commit=False)
        return photo

businesses/views.py
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, DeleteView, FormView

from core import mixins
from . import models, forms


class BusinessDetailView(DetailView):

    """ Business Detail View """

    model = models.Business


class EditBusinessView(mixins.LoggedInOnlyMixin, UpdateView):

    """ Edit Business View """

    model = models.Business
    template_name = "businesses/business_update.html"
    fields = [
        "name",
        "description",
        "address",
        "open_time",
        "close_time",
        "phone",
    ]

    # Business Author가 아니면 접근할 수 없도록 LoggedInOnlyMixin Override
    def test_func(self):
        business = models.Business.objects.get(pk=self.kwargs.get("pk"))
        if self.request.user != business.user:
            return super().test_func(self)
        return True

    def handle_no_permission(self):
        messages.error(self.request, "접근 권한이 없습니다.")
        return super().handle_no_permission(self)

    def get_object(self, queryset=None):
        business = super().get_object(queryset=queryset)
        if business.businessman.pk != self.request.user.pk:
            raise Http404()
        return business

    def get_success_url(self, **kwargs):
        return reverse_lazy("businesses:detail", kwargs={"pk": self.kwargs.get("pk")})


class BusinessPhotosView(mixins.LoggedInOnlyMixin, DetailView):

    """ Business Photos Detail View """

    model = models.Business
    template_name = "businesses/business_photos.html"

    def get_object(self, queryset=None):
        business = super().get_object(queryset=queryset)
        if business.businessman.pk != self.request.user.pk:
            raise Http404()
        return business


class AddPhotoView(mixins.LoggedInOnlyMixin, SuccessMessageMixin, FormView):

    """ Add Photo View """

    model = models.Photo
    template_name = "businesses/photo_create.html"
    fields = (
        "caption",
        "file",
    )
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        photo = form.save(self)
        pk = self.kwargs.get("pk")
        photo.business = models.Business.objects.get(pk=pk)
        photo.save()

        business = photo.business
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("businesses:photos", kwargs={"pk": business.pk}))


class EditPhotoView(mixins.LoggedInOnlyMixin, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "businesses/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "사진을 수정했습니다."
    fields = ("caption",)

    def get_success_url(self):
        business_pk = self.kwargs.get("business_pk")
        return reverse("businesses:photos", kwargs={"pk": business_pk})


class DeletePhotoView(mixins.LoggedInOnlyMixin, SuccessMessageMixin, DeleteView):

    """ Delete Photo View """

    model = models.Photo
    template_name = "businesses/business_delete.html"
    success_message = "사진이 삭제되었습니다."
    pk_url_kwarg = "photo_pk"

    # Business Author가 아니면 접근할 수 없도록 Mixin
    def test_func(self):
        business = models.Business.objects.get(pk=self.kwargs.get("business_pk"))
        if self.request.user != business.user:
            return super().test_func(self)
        return True

    def handle_no_permission(self):
        messages.error(self.request, "접근 권한이 없습니다.")
        return super().handle_no_permission(self)

    def get_success_url(self):
        business_pk = self.kwargs.get("business_pk")
        return reverse("businesses:photos", kwargs={"pk": business_pk})


class DeleteBusinessView(mixins.LoggedInOnlyMixin, UserPassesTestMixin, DeleteView):

    """ Delete Business View """

    model = models.Business
    template_name = "businesses/business_delete.html"
    success_url = reverse_lazy("core:home")

    # Business Author가 아니면 접근할 수 없도록 Mixin
    def test_func(self):
        business = models.Business.objects.get(pk=self.kwargs.get("pk"))
        if self.request.user != business.user:
            return super().test_func(self)
        return True

    def handle_no_permission(self):
        messages.error(self.request, "접근 권한이 없습니다.")
        return super().handle_no_permission(self)


class CreateBusinessView(mixins.LoggedInOnlyMixin, SuccessMessageMixin, FormView):

    form_class = forms.CreateBusinessForm
    template_name = "businesses/business_create.html"
    success_message = "사업체가 성공적으로 등록되었습니다!"

    # Businesman이 아니면 접근할 수 없도록 Mixin
    def test_func(self):
        if self.request.user.businessman:
            return super().test_func(self)
        return True

    def handle_no_permission(self):
        messages.error(self.request, "접근 권한이 없습니다.")
        return super().handle_no_permission(self)

    def form_valid(self, form):
        business = form.save()
        business.businessman = self.request.user
        business.save()
        form.save_m2m()
        messages.success(self.request, "Businesses Uploaded")
        return redirect(reverse("businesses:photos", kwargs={"pk": business.pk}))

templates/businesses/business_create.html
{% extends "base.html" %}

{% block page_title %}
Create Business
{% endblock page_title %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    {% include 'mixins/business/business_form.html' with form=form cta="Create business" %}

</div>

{% endblock content %}

templates/businesses/business_delete.html
{% extends "base.html" %}

{% block page_title %}
Delete Business
{% endblock page_title %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="YES">
</form>

{% endblock content %}

templates/businesses/business_detail.html
{% extends "base.html" %} 

{% block page_title %} 
{{business.name}} 
{% endblock page_title %} 

{% block content %}
<div class="container max-w-full h-75vh flex mb-20">
    <div class="h-full w-1/2 bg-center bg-cover" style="background-image:url({{business.first_photo}})"></div>
    <div class="h-full w-1/2 flex flex-wrap">
        {% for photo in business.get_next_four_photos %}
            <div style="background-image: url({{photo.file.url}})" class="w-1/2 h-auto bg-cover bg-center border-gray-700 border"></div>
        {% endfor %}
    </div>
</div>
<div class="flex flex-col border-b mx-2 py-2 border-gray-400">
    <div class="flex my-2 justify-between">
        <span class=" text-2xl font-medium">{{business.name}}</span>
        <a class="mr-5" href="{{business.businessman.get_absolute_url}}">
            {% include "mixins/user/user_avatar.html" with user=business.businessman h_and_w='w-12 h-12' %}
            <span class="font-medium">{{business.businessman.first_name}}</span>
        </a>
    </div>
    <span class="text-xl">{{business.description}}</span>
</div>
<div class="flex flex-row justify-between mx-2 border-b border-gray-400 py-2">
    <div class="flex flex-col">
        <span><i class="fas fa-map-marker-alt"></i> {{business.address}}</span>
        <span><i class="fas fa-phone-alt"></i> {{business.phone}}</span>
    </div>
    <div class="flex flex-col">
        <span>Open:  {{business.open_time}}</span>
        <span>Close: {{business.close_time}}</span>
    </div>
</div>

<div class="flex my-5">
    {% if business.businessman == user %}
        <a class="btn-link mx-5" href="{% url "businesses:edit" pk=business.pk %}">Edit</a>
        <a class="btn-link mx-5" href="{% url "businesses:delete" pk=business.pk %}">Delete</a>
    {% endif %}
</div>



{% endblock content %}

templates/businesses/business_list.html
{% extends "base.html" %}

{% block page_title %}
    Business
{% endblock page_title %}   

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    {% include "mixins/user/user_avatar.html" with user=user_obj %}
    <div>
        <span>{{user.username}}</span>
    </div>
</div>
    
<div>
    <a href="{% url "businesses:create" %}">Create Business</a>
    {% for business in businesses %}
        <h3>
            <a href="{% url "businesses:detail" pk=business.pk %}">{{business.name}} / {{business.businessman.username}}</a>
        </h3>
    {% endfor %}

    <h5>
    {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}
    Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
    {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}
    </h5>
</div>

{% endblock content %}

templates/businesses/business_photos.html
{% extends 'base.html' %}


{% block page_title %}
    {{business.name}}'s Photos
{% endblock page_title %}


{% block search-bar %}
    
{% endblock search-bar %}
    

{% block content %}
    <div class="container mx-auto flex flex-col ">
        <div class="my-10 w-full">
            <a href="{% url 'businesses:add-photos' business.pk %}" class="btn-link w-1/6 block">Upload Photo</a>
        </div>
    {% for photo in business.photos.all %}
        <div class="border p-6 border-gray-400 flex justify-between">
            <div class="flex items-start">
                <img src="{{phoso.file.url}}" class="w-32 h-32"/>
                <span class="text-xl">{{photo.capition}}</span>
            </div>
            <div class="flex flex-col w-1/5">
                <a class="btn-link bg-green-500 mb-6" href="{% url 'businesses:edit-photos' business.pk photo.pk %}">Edit</a>
                <a class="btn-link bg-red-600" href="{% url 'businesses:delete-photos' business.pk photo.pk %}">Delete</a>
            </div>    
        </div>
    {% endfor %}
        <div class="flex justify-center mt-5">
            <a href="{% url 'businesses:edit' business.pk %}" class="text-green-500 font-medium text-xl">Back to edit business</a>
        </div>
    </div>
{% endblock content %}
    

templates/businesses/business_update.html
{% extends "base.html" %}

{% block page_title %}
    Update Business
{% endblock page_title %}

{% block content %}

<div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    {% include 'mixins/business/business_form.html' with form=form cta="Update business" %}

    <div class="mt-5">
        <a href="{% url 'businesses:photos' business.pk %}" class="text-green-500 font-medium">Edit Photos</a>
    </div>
</div>

{% endblock content %}

templates/businesses/photo_create.html
{% extends "base.html" %}

{% block page_title %}
    Upload photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
     
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
    
        {% include 'mixins/business/business_form.html' with form=form cta="Update photo" %}
            
    </div>
{% endblock content %}

templates/businesses/photo_edit.html
{% extends "base.html" %}

{% block page_title %}
    Update photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
     
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/business/business_form.html' with form=form cta="Update photo" %}
            
    </div>
{% endblock content %}